4.4.2 신경망에서의 기울기
    - 기울기: 가중치 매개변수에 관한 손실 함수의 기울기
    = 손실함수에 대한 미분의 형상은 가중치 형상과 동일

In [12]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

class simpleNet:
    def __init__(self):
        self.W=np.random.randn(2,3) # 정규분포화로 초기화

    def predict(self, x):   # 예측
        return np.dot(x, self.W)

    def loss(self, x, t):   # 손실 함수 연산, x: 입력 데이터, t: 정답 ㅔㄹ이블
        z=self.predict(x)
        y=softmax(z)
        loss=cross_entropy_error(y,t)

        return loss

In [13]:
net=simpleNet()
print(net.W)    # 가중치 매개변수

x=np.array([0.6, 0.9])
p=net.predict(x)
print(p)        # 최댓값의 인덱스

t=np.array([0, 0, 1])   # 정답 레이블
print(net.loss(x, t))

[[-2.17250904 -0.90490188  1.44682235]
 [-1.78497968  1.04497659 -0.69413097]]
[-2.90998713  0.3975378   0.24337554]
0.7927155375475103


In [14]:
def f(W):
    return net.loss(x, t)

dW=numerical_gradient(f, net.W)
print(dW)

# w11=0.2 == w11을 h만큼 늘리면 손실함수의 값이 0.2h만큼 증가한다는 의미
# -> 음의 방향으로 개인해야

# w23=-0.5 == w23을 h만큼 늘리면 손실함수의 값이 0.5만큼 감소한다는 의미
# -> 양의 방향으로 갱신해야

[[ 0.01159821  0.31683335 -0.32843157]
 [ 0.01739732  0.47525003 -0.49264735]]


In [15]:
# 위 def f(W)와 동일한 함수를 간단하게 구현
f=lambda w: net.loss(x, t)
dW=numerical_gradient(f, net.W)